import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { collectFrozenAnchorCorpus, createAnchorBenchmarkCases, runAnchorBenchmarkCases, summarizeAnchorBenchmark } from '../test/fixtures/anchor-benchmark.js';
import { runRetrievalStressBenchmark, summarizeRetrievalStress } from '../test/fixtures/retrieval-stress-benchmark.js';
import { runKnowledgeScaleBenchmark } from '../test/fixtures/knowledge-scale-benchmark.js';
import { runKnowledgeCacheBenchmark } from '../test/fixtures/knowledge-cache-benchmark.js';
import { summarizeTriggerCases } from '../test/fixtures/capture-quality-benchmark.js';
import { runKnowledgeStatusGateBenchmark, statusGateCorpus, summarizeKnowledgeStatusGate } from '../test/fixtures/knowledge-status-gate-benchmark.js';

const resultRoot = path.resolve('bench/results');
await fs.mkdir(resultRoot, { recursive: true });
const selected = new Set<string>();
const argumentsList = process.argv.slice(2);
for (let index = 0; index < argumentsList.length; index++) {
    if (argumentsList[index] !== '--only') throw new Error(`Unknown benchmark argument: ${argumentsList[index]}`);
    const name = argumentsList[index + 1];
    if (!name) throw new Error('--only requires an experiment name');
    selected.add(name);
    index++;
}
const shouldRun = (name: string) => selected.size === 0 || selected.has(name);

if (shouldRun('anchor')) {
    const corpus = collectFrozenAnchorCorpus(path.resolve('../..'));
    const anchorCases = createAnchorBenchmarkCases(corpus);
    const anchorSummary = summarizeAnchorBenchmark(anchorCases, runAnchorBenchmarkCases(anchorCases, { timingIterations: 5, warmupIterations: 1 }));
    await writeResult('anchor', anchorSummary);
}

if (shouldRun('retrieval-stress')) await writeResult('retrieval-stress', summarizeRetrievalStress(await runRetrievalStressBenchmark()));
if (shouldRun('knowledge-scale')) await writeResult('knowledge-scale', await runKnowledgeScaleBenchmark());
if (shouldRun('knowledge-cache')) await writeResult('knowledge-cache', await runKnowledgeCacheBenchmark(20, 3));
if (shouldRun('capture-quality')) await writeResult('capture-quality', summarizeTriggerCases());
if (shouldRun('status-gate')) {
    const statusSummary = summarizeKnowledgeStatusGate(await runKnowledgeStatusGateBenchmark(statusGateCorpus()));
    await writeResult('status-gate', statusSummary);
}

async function writeResult(name: string, summary: unknown): Promise<void> {
    const directory = path.join(resultRoot, name);
    await fs.mkdir(directory, { recursive: true });
    await fs.writeFile(path.join(directory, 'summary.json'), `${JSON.stringify(summary, undefined, 2)}\n`, 'utf8');
    await fs.writeFile(path.join(directory, 'report.md'), `# ${name}\n\nDeterministic benchmark summary generated by \`bench:deterministic\`.\n\n\`\`\`json\n${JSON.stringify(summary, undefined, 2)}\n\`\`\`\n`, 'utf8');
}
